import type { Metadata } from 'next';
import { Schibsted_Grotesk, Poppins } from 'next/font/google';
import './globals.css';

const Pops = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
});

const Schibs = Schibsted_Grotesk({
  subsets: ['latin'],
  variable: '--font-schibsted',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={` ${Pops.variable} ${Schibs.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
